apiVersion: networking.gloo.solo.io/v2
kind: ExternalService
metadata:
  name: httpbin
  namespace: ext-services
spec:
  selector:
    external-service: httpbin
  hosts:
  - httpbin.org
  ports:
  - name: https
    number: 443
    protocol: HTTPS
    clientsideTls: {}   ### upgrade outbound call to HTTPS