apiVersion: admin.gloo.solo.io/v2
kind: Workspace
metadata:
  name: app-team
  namespace: gloo-mesh
spec:
  workloadClusters:
  - name: 'gloo'
    namespaces:
    - name: online-boutique
---
apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: app-team
  namespace: online-boutique
spec:
  # import gateway service for ingress
  importFrom:
  - workspaces:
    - name: ops-team
  # share service discovery and routing to ingress
  exportTo:
  - workspaces:
    - name: ops-team