apiVersion: networking.gloo.solo.io/v2
kind: VirtualGateway
metadata:
  name: gloo-gateway
  namespace: istio-ingress
spec:
  workloads:
    - selector:
        labels:
          istio: ingressgateway
        namespace: istio-ingress
  listeners: 
    # HTTP port
    - http: {}
      port:
        number: 80
      allowedRouteTables:
        - host: '*'
          selector:
            workspace: ops-team
    # HTTPS port
    - http: {}
      port:
        number: 443
      tls:
        mode: SIMPLE
        secretName: tls-secret # NOTE
      allowedRouteTables:
        - host: '*'
          selector:
            workspace: ops-team