apiVersion: admin.gloo.solo.io/v2
kind: GatewayLifecycleManager
metadata:
  name: istio-ingressgateway
  namespace: gloo-mesh
spec:
  installations:
      # The revision for this installation, such as 1-14
    - gatewayRevision: 1-16
      # List all workload clusters to install Istio into
      clusters:
      - name: gloo
        # If set to true, the spec for this revision is applied in the cluster
        activeGateway: false
      istioOperatorSpec:
        # No control plane components are installed
        profile: empty
        # Solo.io Istio distribution repository; required for Gloo Istio.
        # You get the repo key from your Solo Account Representative.
        hub: us-docker.pkg.dev/gloo-mesh/istio-workshops
        # The Solo.io Gloo Istio tag
        tag: 1.16.2-solo
        values:
          gateways:
            istio-ingressgateway:
              injectionTemplate: gateway
          global:
            network: istio-network
        components:
          ingressGateways:
          # Enable the default ingress gateway
            - name: istio-ingressgateway
              # Deployed to gloo-mesh-gateways by default
              namespace: istio-ingress
              enabled: true
              label:
                # Set a unique label for the gateway. This is required to
                # ensure Gateways can select this workload
                istio: ingressgateway
                app: istio-ingressgateway
                revision: 1-16
              k8s:
                serviceAnnotations:
                  service.beta.kubernetes.io/aws-load-balancer-type: "external"
                  service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
                  service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
                service:
                  type: LoadBalancer
                  selector:
                    istio: ingressgateway
                  # Default ports
                  ports:
                    # Port for health checks on path /healthz/ready.
                    # For AWS ELBs, this port must be listed first.
                    - name: status-port
                      port: 15021
                      targetPort: 15021
                    # Main HTTP ingress port
                    - port: 80
                      targetPort: 8080
                      name: http2
                    # Main HTTPS ingress port
                    - port: 443
                      targetPort: 8443
                      name: https
      # The revision for this installation, such as 1-14
    - gatewayRevision: 1-17
      # List all workload clusters to install Istio into
      clusters:
      - name: gloo
        # If set to true, the spec for this revision is applied in the cluster
        activeGateway: true
      istioOperatorSpec:
        # No control plane components are installed
        profile: empty
        # Solo.io Istio distribution repository; required for Gloo Istio.
        # You get the repo key from your Solo Account Representative.
        hub: us-docker.pkg.dev/gloo-mesh/istio-workshops
        # The Solo.io Gloo Istio tag
        tag: 1.17.1-solo
        values:
          gateways:
            istio-ingressgateway:
              injectionTemplate: gateway
          global:
            network: istio-network
        components:
          ingressGateways:
          # Enable the default ingress gateway
            - name: istio-ingressgateway
              # Deployed to gloo-mesh-gateways by default
              namespace: istio-ingress
              enabled: true
              label:
                # Set a unique label for the gateway. This is required to
                # ensure Gateways can select this workload
                istio: ingressgateway
                app: istio-ingressgateway
                revision: 1-17
              k8s:
                serviceAnnotations:
                  service.beta.kubernetes.io/aws-load-balancer-type: "external"
                  service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
                  service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
                service:
                  type: LoadBalancer
                  selector:
                    istio: ingressgateway
                  # Default ports
                  ports:
                    # Port for health checks on path /healthz/ready.
                    # For AWS ELBs, this port must be listed first.
                    - name: status-port
                      port: 15021
                      targetPort: 15021
                    # Main HTTP ingress port
                    - port: 80
                      targetPort: 8080
                      name: http2
                    # Main HTTPS ingress port
                    - port: 443
                      targetPort: 8443
                      name: https