# workspace configuration
apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: ops-team
  # placed in the administrative namespace
  namespace: istio-ingress
spec:
  # import service discovery from app-team and checkout team
  importFrom:
  - workspaces:
    - name: app-team
    - name: checkout-team
  # export service discovery to any workspace that needs ingress
  exportTo:
  - workspaces:
    - name: "*"
  # for mutli cluster routing
  options:
    eastWestGateways:
    - selector:
        labels:
          istio: eastwestgateway